### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by Erozen777** [AtomicBlom/ChunkExplorer#2]
Hello I recently downloaded this mod, currently everytime I launch the game I'm getting the error "[07/3/2016 07:04:44 AM] [main/WARN] [FML]: Zip file 1.7.10.chunkexplorer-1.0.jar failed to read properly, it will be ignored."

Currently require it to purge a map of a lot of command blocks.

Any ideas to resolve this?

Running 1.7.10
Forge 10.13.4.1558

**Comment by Erozen777** [comment]
Apologies, mod worked without issue when I redownloaded from GitHub. Original download from curse must have corrupted somehow.

Thank you for the utility!

**Comment by AtomicBlom** [comment]
Glad to hear you were able to resolve it.
